name: Code Quality
on: push

jobs:
    code-quality:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - name: Install Dependencies
              run: npm ci

            - name: Lint Files
              run: npm run lint

            - name: Check Types
              run: npm run check-types

            - name: Run Tests
              run: npm run test-only
